# This is a basic workflow to Package the addon with Github Actions

name: Package Addon

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    tags:
    - '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "release"
  release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Clone project
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # once cloned, we just run the GitHub Action for the packager project
    - name: Package and release
      uses: BigWigsMods/packager@v2
